"""Data access layer for chats."""

from datetime import datetime, timezone
from typing import Sequence
from uuid import UUID

from sqlalchemy import exists, func, or_, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from app.chats.models import (
    Chat,
    ChatMember,
    ChatReadState,
    DirectChat,
    Message,
    MessageAttachment,
)


async def get_direct_chat(db: AsyncSession, user_a: UUID, user_b: UUID) -> Chat | None:
    """Look up an existing direct chat between two users.

    Args:
        db: Async database session.
        user_a: One of the two participants, in either order.
        user_b: The other participant, in either order.

    Returns:
        Chat | None: The chat if found, otherwise None.
    """
    user_lo, user_hi = sorted([user_a, user_b])
    result = await db.execute(
        select(Chat)
        .join(DirectChat, Chat.id == DirectChat.chat_id)
        .where(DirectChat.user_lo == user_lo, DirectChat.user_hi == user_hi)
    )
    return result.scalar_one_or_none()


async def create_direct_chat(
    db: AsyncSession,
    creator_id: UUID,
    peer_id: UUID,
) -> Chat:
    """Create a chat with its direct-chat and membership rows in one transaction.

    Args:
        db: Async database session.
        creator_id: User initiating the chat.
        peer_id: The other participant (equal to creator_id for a self-chat).

    Returns:
        Chat: The newly created chat.

    Raises:
        IntegrityError: If a direct chat between this pair already exists.
    """
    user_lo, user_hi = sorted([creator_id, peer_id])
    chat = Chat(created_by=creator_id)
    db.add(chat)
    await db.flush()
    if creator_id == peer_id:
        members = [ChatMember(chat_id=chat.id, user_id=creator_id)]
    else:
        members = [
            ChatMember(chat_id=chat.id, user_id=creator_id),
            ChatMember(chat_id=chat.id, user_id=peer_id),
        ]
    db.add_all(
        [*members, DirectChat(chat_id=chat.id, user_lo=user_lo, user_hi=user_hi)]
    )
    try:
        await db.commit()
    except IntegrityError:
        await db.rollback()
        raise
    return chat


async def list_user_chats(
    db: AsyncSession,
    user_id: UUID,
) -> Sequence[Chat]:
    """Look up all chats the given user is a member of.

    Args:
        db: Async database session.
        user_id: Id of the user to look up chats for.

    Returns:
        Sequence[Chat]: All chats the user is a member of.
    """
    result = await db.execute(
        select(Chat)
        .join(ChatMember, Chat.id == ChatMember.chat_id)
        .where(ChatMember.user_id == user_id)
    )

    return result.scalars().all()


async def get_last_messages(
    db: AsyncSession, chat_ids: Sequence[UUID]
) -> dict[UUID, Message]:
    """Look up the most recent message for each of the given chats.

    Args:
        db: Async database session.
        chat_ids: Chats to look up the last message for.

    Returns:
        dict[UUID, Message]: Latest message per chat id; chats with no
        messages yet are simply absent from the dict.
    """
    result = await db.execute(
        select(Message)
        .where(Message.chat_id.in_(chat_ids))
        .distinct(Message.chat_id)
        .order_by(Message.chat_id, Message.created_at.desc())
    )
    return {message.chat_id: message for message in result.scalars().all()}


async def list_chat_members(db: AsyncSession, chat_id: UUID) -> Sequence[ChatMember]:
    """Fetch all members of a given chat.

    Args:
        db: Async database session.
        chat_id: Id of the chat.

    Returns:
        Sequence[ChatMember]: A list of chat member records.
    """
    results = await db.execute(select(ChatMember).where(ChatMember.chat_id == chat_id))
    return results.scalars().all()


async def is_user_in_chat(db: AsyncSession, chat_id: UUID, user_id: UUID) -> bool:
    """Check if a specific user is a member of a chat.

    Args:
        db: Async database session.
        chat_id: Id of the chat.
        user_id: Id of the user.

    Returns:
        bool: True if the user is a member, False otherwise.
    """
    result = await db.execute(
        select(
            exists().where(
                ChatMember.chat_id == chat_id,
                ChatMember.user_id == user_id,
            )
        )
    )
    return result.scalar()


async def create_message(
    db: AsyncSession, chat_id: UUID, sender_id: UUID, body: str, client_msg_id: UUID
) -> tuple[Message, bool]:
    """Create a new message or return an existing one if client_msg_id is duplicated.

    Args:
        db: Async database session.
        chat_id: Id of the chat where message is sent.
        sender_id: Id of the user sending the message.
        body: Text content of the message.
        client_msg_id: Idempotency key generated by the client.

    Doesn't commit — callers that also need to attach files in the same
    request (e.g. `send_message`) do that first and commit once at the
    end, so a crash between the two can never save one without the other.

    Returns:
        tuple[Message, bool]: The message row, and True if it was newly
        created (False if an existing row with this client_msg_id was
        returned instead) — callers use this to avoid redoing side effects
        like attaching files on a retried request.
    """
    msg = Message(
        chat_id=chat_id, sender_id=sender_id, body=body, client_msg_id=client_msg_id
    )
    try:
        async with db.begin_nested():
            db.add(msg)
            await db.flush()
        return msg, True
    except IntegrityError:
        result = await db.execute(
            select(Message).where(
                Message.sender_id == sender_id,
                Message.client_msg_id == client_msg_id,
            )
        )
        existing_message = result.scalar_one_or_none()

        if existing_message is None:
            raise

        return existing_message, False


async def get_chat_messages(
    db: AsyncSession, chat_id: UUID, limit: int, before_msg_id: UUID | None
) -> list[Message]:
    """Fetch paginated messages history for a specific chat.

    Args:
        db: Async database session.
        chat_id: Id of the chat to get messages of.
        limit: Max number of messages to return.
        before_msg_id: Optional cursor; if provided, returns messages
            created strictly before this message ID.

    Returns:
        list[Messages]: A list of messages objects, ordered from newest to oldest.
    """
    stmt = (
        select(Message)
        .where(Message.chat_id == chat_id)
        .order_by(Message.id.desc())
        .limit(limit)
    )

    if before_msg_id:
        stmt = stmt.where(Message.id < before_msg_id)

    result = await db.execute(stmt)
    return result.scalars().all()


async def add_attachments(
    db: AsyncSession, message_id: UUID, file_ids: Sequence[UUID]
) -> None:
    """Link a message to its attachment files.

    Doesn't commit — see `create_message`'s docstring for why.

    Args:
        db: Async database session.
        message_id: Id of the message.
        file_ids: Ids of files (owned by file-orchestrator) to attach.
    """
    if not file_ids:
        return
    db.add_all(
        [MessageAttachment(message_id=message_id, file_id=fid) for fid in file_ids]
    )


async def get_attachment_ids(db: AsyncSession, message_id: UUID) -> list[UUID]:
    """Get the attachment file ids for a single message.

    Args:
        db: Async database session.
        message_id: Id of the message.

    Returns:
        list[UUID]: Ids of attached files, in no particular order.
    """
    result = await db.execute(
        select(MessageAttachment.file_id).where(
            MessageAttachment.message_id == message_id
        )
    )
    return list(result.scalars().all())


async def get_attachment_ids_bulk(
    db: AsyncSession, message_ids: Sequence[UUID]
) -> dict[UUID, list[UUID]]:
    """Get attachment file ids for a batch of messages in a single query.

    Args:
        db: Async database session.
        message_ids: Ids of messages to look up attachments for.

    Returns:
        dict[UUID, list[UUID]]: Attachment file ids per message id; messages
        with no attachments are simply absent from the dict.
    """
    result = await db.execute(
        select(MessageAttachment).where(MessageAttachment.message_id.in_(message_ids))
    )
    mapping: dict[UUID, list[UUID]] = {}
    for row in result.scalars().all():
        mapping.setdefault(row.message_id, []).append(row.file_id)
    return mapping


async def get_message(
    db: AsyncSession, chat_id: UUID, message_id: UUID
) -> Message | None:
    """Get a message by id, scoped to a chat.

    Args:
        db: Async database session.
        chat_id: Id of the chat the message must belong to.
        message_id: Id of the message.

    Returns:
        Message | None: The message if found in this chat, otherwise None.
    """
    result = await db.execute(
        select(Message).where(Message.id == message_id, Message.chat_id == chat_id)
    )
    return result.scalar_one_or_none()


async def update_message_body(db: AsyncSession, message: Message, body: str) -> Message:
    """Update a message's text and stamp it as edited.

    Args:
        db: Async database session.
        message: The message row to update.
        body: New text content.

    Returns:
        Message: The updated message.
    """
    message.body = body
    message.edited_at = datetime.now(timezone.utc)
    await db.commit()
    return message


async def soft_delete_message(db: AsyncSession, message: Message) -> Message:
    """Mark a message deleted and clear its text.

    Args:
        db: Async database session.
        message: The message row to delete.

    Returns:
        Message: The updated (deleted) message.
    """
    message.is_deleted = True
    message.body = ""
    await db.commit()
    return message


async def search_messages(
    db: AsyncSession, chat_id: UUID, query: str, limit: int
) -> list[Message]:
    """Search non-deleted messages in a chat by a case-insensitive substring.

    Args:
        db: Async database session.
        chat_id: Id of the chat to search within.
        query: Substring to match against the message body.
        limit: Maximum number of rows to return.

    Returns:
        list[Message]: Matching messages, newest first, capped at limit.
    """
    stmt = (
        select(Message)
        .where(
            Message.chat_id == chat_id,
            Message.is_deleted.is_(False),
            Message.body.ilike(f"%{query}%"),
        )
        .order_by(Message.created_at.desc())
        .limit(limit)
    )
    result = await db.execute(stmt)
    return result.scalars().all()


async def get_read_state(
    db: AsyncSession, chat_id: UUID, user_id: UUID
) -> ChatReadState | None:
    """Get a user's read state for a chat.

    Args:
        db: Async database session.
        chat_id: Id of the chat.
        user_id: Id of the user.

    Returns:
        ChatReadState | None: The read state if it exists, otherwise None.
    """
    return await db.get(ChatReadState, {"chat_id": chat_id, "user_id": user_id})


async def set_read_state(
    db: AsyncSession,
    chat_id: UUID,
    user_id: UUID,
    message_id: UUID,
    message_created_at: datetime,
) -> ChatReadState:
    """Create or advance a user's read state for a chat.

    `last_read_at` is the *marked message's own* `created_at`, not the
    time of this call — unread counts compare against it, so using
    "now" here would wrongly mark every message sent between the
    referenced message and this API call as read too (e.g. if the
    client marks an older message read, or the call arrives late).

    Never moves the cursor backward: a stale or out-of-order call
    marking an older message read than what's already recorded is a
    no-op, not a regression that un-reads newer messages.

    Args:
        db: Async database session.
        chat_id: Id of the chat.
        user_id: Id of the user marking it read.
        message_id: Id of the last message read.
        message_created_at: `created_at` of the message being marked read.

    Returns:
        ChatReadState: The current (possibly unchanged) read state.
    """
    state = await get_read_state(db, chat_id, user_id)
    if state is None:
        state = ChatReadState(chat_id=chat_id, user_id=user_id)
        db.add(state)
    elif state.last_read_at >= message_created_at:
        return state

    state.last_read_message_id = message_id
    state.last_read_at = message_created_at
    await db.commit()
    return state


async def count_unread_bulk(
    db: AsyncSession, user_id: UUID, chat_ids: Sequence[UUID]
) -> dict[UUID, int]:
    """Count unread messages per chat for a user in a single query.

    A message counts as unread if it wasn't sent by this user and was
    created after their last recorded read timestamp for that chat (or
    every message from others counts if they've never read the chat).

    Args:
        db: Async database session.
        user_id: Id of the user to count unread messages for.
        chat_ids: Chats to compute unread counts for.

    Returns:
        dict[UUID, int]: Unread count per chat id; chats with zero unread
        (including chats with no messages at all) are simply absent.
    """
    read_at_subquery = (
        select(ChatReadState.last_read_at)
        .where(
            ChatReadState.chat_id == Message.chat_id,
            ChatReadState.user_id == user_id,
        )
        .correlate(Message)
        .scalar_subquery()
    )
    stmt = (
        select(Message.chat_id, func.count())
        .where(
            Message.chat_id.in_(chat_ids),
            Message.sender_id != user_id,
            Message.is_deleted.is_(False),
            or_(read_at_subquery.is_(None), Message.created_at > read_at_subquery),
        )
        .group_by(Message.chat_id)
    )
    result = await db.execute(stmt)
    return dict(result.all())


async def list_chat_peer_ids(
    db: AsyncSession,
    user_id: UUID,
) -> Sequence[UUID]:
    """Return users who share at least one chat with the given user.

    Args:
        db: Async database session.
        user_id: ID of the user whose chat peers should be found.

    Returns:
        Sequence[UUID]: Unique IDs of other chat members, ordered by ID.
    """
    user_chat_ids = select(ChatMember.chat_id).where(ChatMember.user_id == user_id)

    result = await db.execute(
        select(ChatMember.user_id)
        .where(
            ChatMember.chat_id.in_(user_chat_ids),
            ChatMember.user_id != user_id,
        )
        .distinct()
        .order_by(ChatMember.user_id)
    )

    return result.scalars().all()
