port: 7880

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000

redis:
  address: 127.0.0.1:6379

keys:
  devkey: devsecret

turn:
  enabled: true
  domain: rtc.example.com
  tls_port: 443
  udp_port: 3478

room:
  auto_create: true
