services:
  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  identity:
    build: ../src/services/identity
    container_name: identity
    env_file: ../src/services/identity/.env
    depends_on:
      db:
        condition: service_healthy
  api-gateway:
    build: ../src/services/api-gateway
    container_name: api-gateway
    env_file: ../src/services/api-gateway/.env
    ports:
      - "8000:8000"
    # TODO: добавить identity собственный healthcheck и заменить
    # зависимость на condition: service_healthy
    depends_on:
      - identity
  communication:
    build: ../src/services/communication
    container_name: communication
    env_file: ../src/services/communication/.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
