"""allow self chats

Revision ID: 47db32620621
Revises: 4999b046924e
Create Date: 2026-07-16 00:48:18.702573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47db32620621'
down_revision: Union[str, Sequence[str], None] = '4999b046924e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_direct_chats_pair_ordered", "direct_chats", type_="check")
    op.create_check_constraint("ck_direct_chats_pair_ordered", "direct_chats", "user_lo <= user_hi")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_direct_chats_pair_ordered", "direct_chats", type_="check")
    op.create_check_constraint("ck_direct_chats_pair_ordered", "direct_chats", "user_lo < user_hi")
    # ### end Alembic commands ###
